name: Build and Release

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8.0.332+9
        cache: 'maven'
    - name: Get version
      id: version
      run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - name: Get changelog
      id: changelog
      run: echo ::set-output name=changelog::$(git log --pretty=format:"%h %s" $(git describe --tags --abbrev=0)..HEAD)
    - name: "Compilazione"
      run: mvn compile
    - name: "Testing"
      run: mvn test
    - name: "Analisi statica"
      run: mvn verify
    - name: "Coveralls"
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: target/site/jacoco/jacoco.xml
    